---
- name: Creano carpeta para Helm
  shell: mkdir -p /Helm

- name: Descargando Helm 3
  shell: curl -fsSL -o /Helm/get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

- name: Otorgando permisos al instaldor
  shell: chdir=/Helm chmod 700 get_helm.sh

- name: Ejecutando el script
  shell: chdir=/Helm ./get_helm.sh
