---
- name: Instalando yum-utils
  yum:
    name: yum-utils
    state: present

- name: Instalando device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: present

- name: Instalando lvm2
  yum:
    name: lvm2
    state: present

- name: Instalando httpd
  yum:
    name: httpd
    state: present

- name: Iniciando el servicio httpd
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: yes

- name: Creando carpeta para Kubernetes
  ansible.builtin.file:
    path: /kubernetes
    state: directory

- name: Configurandio el repositorio de Kubernetes
  shell: |
    cat <<EOF > /etc/yum.repos.d/kubernetes.repo
    [kubernetes]
    name=Kubernetes
    enabled=1
    gpgcheck=0
    repo_gpgcheck=0
    baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    EOF

- name: Instalando kubelet
  yum:
    name: kubelet-1.20.0-0
    state: present

- name: Instalando kubeadm
  yum:
    name: kubeadm-1.20.0-0
    state: present

- name: Instalando kubectl
  yum:
    name: kubectl-1.20.0-0
    state: present

- name: Iniciando el servicio kubelet y habilitandolo
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes

- name: Configurando la red
  shell: |
    cat <<EOF > /etc/sysctl.d/k8s.conf
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    EOF

- name: Se modifica el kernel
  shell: sysctl --system

- name: Se configura el firewall
  shell: echo '1' > /proc/sys/net/ipv4/ip_forward

- name: Se desactiva Selinux
  shell: setenforce 0

- name: Se configura Selinux
  shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Se configura fstab
  shell: sed -i '/swap/d' /etc/fstab

- name: Se desactiva swap
  shell: swapoff -a

- name: Creando el cluster de kubernetes
  shell: kubeadm init --apiserver-advertise-address={{ ip }} --pod-network-cidr=10.244.0.0/16
  ignore_errors: yes

- name: Se crea un directorio para el archivo de configuracion de Kubernetes
  ansible.builtin.file:
    path: ~/kube
    state: directory

- name: Se crea la carpeta del archivo de configuración de Kubernetes
  shell: mkdir -p ~/.kube

- name: Se copia el archivo de configuracion a la ruta anterior
  shell: cp /etc/kubernetes/admin.conf ~/.kube/config

- name: Se aplican los cambios de red a Kubernetes
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: El nodo maestro ahora puede ser un nodo trabajador
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  ignore_errors: yes

- name: Creando el alias k=kubectl
  lineinfile:
    path: ~/.bashrc
    line: alias k='kubectl'
    insertbefore: BOF
 
- name: Creando el alias ksys=kubectl -n kube-sys
  lineinfile:
    path: ~/.bashrc
    line: alias ksys='kubectl -n kube-system'
    insertbefore: BOF

- name: Creando el alias ki=kubectl -n infra
  lineinfile:
    path: ~/.bashrc
    line: alias ksys='kubectl -n infra'
    insertbefore: BOF
